Travel inquiry and package booking system/dj_19/api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from dj_19 import views
from api import views

urlpatterns = [
    # Site Info
    path('get-site-info/', views.get_site_info, name='get_site_info'),
    path('slider-and-gallery/', views.slider_and_gallery, name='slider_and_gallery'),
    path('category-and-country/', views.category_and_country, name='category_and_country'),
    path('page/<slug:slug>/', views.page_content, name='page_content'),
    path('testimonial/', views.get_testimonial, name='get_testimonial'),
    # services List
    path('services/', views.get_services, name='get_services'),
    path('services-detail/<int:id>', views.services_detail, name='services_detail'),
    # Travel Guides
    path('travel-guides/', views.travel_guides, name='travel_guides'),
    path('guides-detail/<int:id>', views.guides_detail, name='guides_detail'),
    # Careers
    path('jobs/', views.job_list, name='job_list'),
    path('jobs-detail/<int:id>', views.job_details, name='job_details'),
    path("apply-job/", views.apply_job, name="apply-job"),
    # Booking Enquiry
    path("booking-enquiry/", views.booking_enquiry, name="booking-enquiry"),
]
 

Travel inquiry and package booking system/dj_19/dj_19/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from dj_19 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('booking-list/', views.bookingList, name='bookingList'),
    path('get-travel-enquiry/', views.getTravelEnquiry, name='getTravelEnquiry'),
    path('travel-enquiry/', views.travelEnquiry, name='travelEnquiry'),
    path('get-quotation/', views.getQuotation, name='getQuotation'),
    path('delete-travel-enquiry/<int:id>/', views.deleteUserEnquiry, name='deleteUserEnquiry'),
    path('user-profile/', views.userProfile, name='userProfile'),
    path('change-password/', views.changePassword, name='changePassword'),
    path('user-gallery/', views.userGallery, name='userGallery'),
    path('delete-user-image/<int:id>/', views.deleteUserImage, name='deleteUserImage'),
    path('user-signup/', views.registrationsPage, name='registrationsPage'),
    path('registrations/', views.registrations, name='registrations'),
    path('thank-you/', views.thankYouPage, name='thankYouPage'),
    path('login/', views.loginPage, name='loginPage'),
    path('logout/', views.logoutUser, name='logout'),
    path('about/', views.about, name='about'),
    path('package-confirmation/', views.packageConfirmation, name='packageConfirmation'),
    path('booking-confirmation/<int:id>/', views.bookingConfirmation, name='bookingConfirmation'),
    path('razorpay-success',views.razorpaySuccess,name='razorpaySuccess'),
    path('bookingReceipt/<int:id>/', views.bookingReceipt, name='bookingReceipt'),
    path('download-receipt/<int:id>/',views.downloadReceiptPDF,name='downloadReceiptPDF'),
    path('pay-now/', views.payNow, name='payNow'),
    path('services/', views.services, name='services'),
    path('services/<int:id>/', views.servicesDetails, name='servicesDetails'),
    path('packages/', views.packages, name='packages_list'),
    path('packages/<int:category_id>/', views.packages, name='packages'),
    path('packages/<slug:slug>/', views.packagesInfo, name='packagesInfo'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blogDetails, name='blogDetails'),
    path('contact/', views.contact, name='contact'),
    path('send-enquiry/', views.userSendEnquiry, name='userSendEnquiry'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('booking/', views.booking, name='booking'),
    path('booking/<int:package_id>/', views.booking, name='booking_with_id'),
    path('destination/', views.destination, name='destination'),
    path('destination/<int:country_id>/', views.destination, name='destination_country_id'),
    path('explore-tour/', views.exploreTour, name='exploreTour'),
    path('travel-guides/', views.travelGuides, name='travelGuides'),
    path('guide/<int:id>/', views.travelGuidesInfo, name='travelGuidesInfo'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/<int:category_id>/', views.gallery, name='gallery_category_id'),
    path('careers/', views.careers, name='careers'),
    path('careers/<int:id>/', views.careersDetails, name='careersDetails'),
    path('apply-job/<int:id>/', views.applyJob, name='applyJob'),
    path('<slug:slug>/', views.cmsContent, name='cmsContent'),
    path('api/',include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Travel inquiry and package booking system/dj_19/bookings/models.py
from django.db import models 
from Trave_Packages_Management.models import QuotationInfo,TravelPackage,TravelEnquiry
from django.contrib.auth.models import User
from setting.models import Countries,Categories
from tinymce.models import HTMLField

class BookingList(models.Model):
    HOTEL_TYPE_CHOICES = [
        ('5_star', '5 Star'),
        ('4_star', '4 Star'),
        ('3_star', '3 Star'),
        ('2_star', '2 Star'),
        ('1_star', '1 Star'),
    ]

    booking_type = models.CharField(
        max_length=50,
        choices=[('Quotation', 'Quotation'), ('Package', 'Package')],
        default='Quotation'
    )
    # User Information
    TravelEnquiry = models.ForeignKey(TravelEnquiry, on_delete=models.SET_NULL, null=True, blank=True, related_name='booking_TravelEnquiry')
    quotationInfo = models.ForeignKey(QuotationInfo, on_delete=models.SET_NULL, null=True, blank=True, related_name='booking_quotationInfo')
    travelPackage = models.ForeignKey(TravelPackage, on_delete=models.SET_NULL, null=True, blank=True, related_name='booking_travelPackage')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='booking_users')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_no = models.CharField(max_length=20)
    departure_date = models.DateField()
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, blank=True, related_name='booking_categories')
    destination = models.CharField(max_length=100)
    country = models.ForeignKey(Countries, on_delete=models.SET_NULL, null=True, blank=True, related_name='booking_country')
    duration = models.IntegerField(help_text="Duration in days")
    no_person = models.IntegerField(help_text="No Person for the enquiry include chldren")
    hotel_type = models.CharField(max_length=10, choices=HOTEL_TYPE_CHOICES, default='3_star')
    tourdetails = HTMLField(help_text="Enter please send your tour details")
    # Billing Information
    order_id = models.CharField(max_length=255, null=True, blank=True)
    payment_id = models.CharField(max_length=255, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default="0.00")
    sub_total_amount = models.DecimalField(max_digits=10, decimal_places=2, default="0.00")
    other_charges_amount = models.DecimalField(max_digits=10, decimal_places=2, default="0.00")
    other_charges_info = models.TextField(blank=True, null=True)
    payment_status = models.TextField(blank=True, null=True)
    payment_status = models.CharField(
        max_length=50,
        choices=[('failed', 'failed'), ('pending', 'pending'), ('success', 'success')],
        default='pending'
    )
    #  Update Information
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True) 

Travel inquiry and package booking system/dj_19/templates/pages/userInfo/booking_list.html
{% extends 'main_templates.html' %}
{% block content %}
{% load static %}
<!-- Header Start -->
{% include 'include/breadcrumb.html' %}
<!-- Header End -->
<!-- 404 Start -->
<div class="container-fluid py-5">
   <div class="container py-0 text-center">
      <div class="row">
         {% include 'pages/userInfo/side_bar.html' %}
         <div class="col-lg-10 col-md-12">
            <div class="row">
               <div class="col-lg-12 col-md-12">
                  <div class="card text-start">
                     <div class="card-header">
                        Booking List
                        <div class="float-right"><a href="{% url 'booking' %}" class="btn btn-primary rounded-pill py-0 px-4 ms-lg-4">Book Now</a></div>
                     </div>
                     <div class="card-body">
                        <table id="example" class="example table table-striped table-bordered">
                           <thead>
                              <tr>
                                 <th>Booking ID</th>
                                 <th>Name</th>
                                 <th>Phone</th>
                                 <th>Departure date</th>  
                                 <th>Pay Amount</th>
                                 <th>Pay Date</th>
                                 <th>Payment Status</th>
                                 <th>Action</th>

                              </tr>
                           </thead>
                           <tbody>
                              {% for booking in booking_list %}
                              <tr>
                                 <td><a href="{% url 'bookingReceipt' booking.id  %}">{{booking.order_id}}</a></td>
                                 <td>{{booking.name}}</td>
                                 <td>{{booking.phone_no}}</td>
                                 <td>{{ booking.departure_date}}</td> 
                                 <td>{{booking.total_amount}}</td>
                                 <td>{{booking.created_at|date:"M d, Y"}}</td>
                                 <td class="{% if booking.payment_status == 'success' %}text-success{% else %}text-danger{% endif %}">{{booking.payment_status}}</td>
                                 <td>
                                    <a href="{% url 'bookingReceipt' booking.id  %}" class="btn btn-primary btn-sm"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                    <a href="{% url 'downloadReceiptPDF' booking.id  %}" class="btn btn-success btn-sm"><i class="fa fa-download" aria-hidden="true"></i></a>
                                 </td>
                              </tr>
                              {% endfor %}
                               
                           </tbody> 
                        </table>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- 404 End -->
{% endblock %}

Travel inquiry and package booking system/dj_19/templates/pages/userInfo/change_password.html
{% extends 'main_templates.html' %}
{% block content %}
{% load static %}
<!-- Header Start -->
{% include 'include/breadcrumb.html' %}
<!-- Header End -->

<!-- 404 Start -->
<div class="container-fluid py-5">
   <div class="container py-0 text-center">
            <div class="row msg">
                  <div class="col-lg-12 col-md-12 mx-auto">
                        {% if messages %}
                              {% for message in messages %}
                                    <div class="alert {% if message.tags == 'error' %} alert-danger {% else  %}  alert-success {% endif %} alert-dismissible">
                                          {{ message }} 
                                    </div>
                              {% endfor %}
                        {% endif %}
                  </div>
            </div>
         <div class="row">
            {% include 'pages/userInfo/side_bar.html' %}
            <div class="col-lg-10 col-md-12">
                  <div class="row">
                        <div class="col-lg-12 col-md-12">
                              <div class="card text-start">
                                 <div class="card-header">
                                    Change Password
                                 </div>
                                 <div class="card-body"> 
                                    <form action="" method="post" enctype="multipart/form-data" id="changePasswordForm">
                                          {% csrf_token %}
                                       <div class="row">
                                             <div class="col-lg-6 col-md-6">
                                                   <div class="form-group">
                                                      <label>New Password:</label>
                                                      <input type="password" name="old_password" id="old_password" class="form-control">
                                                   </div>
                                             </div>
                                             <div class="col-lg-6 col-md-6">
                                                   <div class="form-group">
                                                      <label>Confirm Password:</label>
                                                      <input type="password" name="new_password1" id="new_password1" class="form-control">
                                                   </div>
                                             </div>
                                       </div>
                                       <div class="row mt-3">
                                             <div class="col-lg-6 col-md-6">
                                                   <div class="form-group">
                                                      <label>Old Password:</label>
                                                      <input type="password" name="new_password2" id="new_password2" class="form-control">
                                                   </div>
                                             </div> 
                                       </div>
                                        
                                       <div class="row mt-3">
                                             <div class="col-lg-12 col-md-12 text-center"> 
                                                <button type="submit" class="btn btn-primary rounded-pill py-2 px-4 ms-lg-4" id="chng_butt_frm">Update Password</button>
                                             </div>
                                             
                                       </div>
                                    </form>
                                 </div>
                              </div>
                        </div>
                         
                  </div>

            </div>
         </div>
   </div>
</div>
<!-- 404 End -->
{% endblock %}

Travel inquiry and package booking system/dj_19/templates/pages/userInfo/dashboard.html
{% extends 'main_templates.html' %}
{% block content %}
{% load static %}
<!-- Header Start -->
{% include 'include/breadcrumb.html' %}
<!-- Header End -->

<!-- 404 Start -->
<div class="container-fluid py-5">
   <div class="container py-0 text-center">
         <div class="row">
            {% include 'pages/userInfo/side_bar.html' %}
            <div class="col-lg-10 col-md-12">
                  <div class="row">
                        <div class="col-lg-4 col-md-12">
                              <div class="card">
                                 <div class="card-header">
                                    Total Booking
                                 </div>
                                 <div class="card-body">
                                    <!-- Your main content goes here -->
                                    <p>{{total_booking}}</p>
                                 </div>
                              </div>
                        </div>
                        <div class="col-lg-4 col-md-12">
                              <div class="card">
                                 <div class="card-header">
                                    Total Booking Pending 
                                 </div>
                                 <div class="card-body">
                                    <!-- Your main content goes here -->
                                    <p>{{total_enquiry}}</p>
                                 </div>
                              </div>
                        </div>
                        <div class="col-lg-4 col-md-12">
                              <div class="card">
                                 <div class="card-header">
                                    Total Spent Amount
                                 </div>
                                 <div class="card-body">
                                    <!-- Your main content goes here -->
                                    <p><i class="fa fa-rupee-sign"></i> {{total_booking_amount|floatformat:2}}</p>
                                 </div>
                              </div>
                        </div>
                  </div>
                  <div class="row mt-3">
                        <div class="col-lg-12 col-md-12 text-center">
                           <a href="{% url 'booking' %}" class="btn btn-primary rounded-pill py-2 px-4 ms-lg-4">Book Now</a>
                        </div>
                  </div>

            </div>
         </div>
   </div>
</div>
<!-- 404 End -->
{% endblock %}

Travel inquiry and package booking system/dj_19/templates/pages/userInfo/side_bar.html
{% load static %}
<div class="col-lg-2 col-md-12"> 
    <div class="d-flex">
        <div class="list-group w-100 text-center">
            <a href="#" class="list-group-item list-group-item-action"> 
                <b>{{ request.user.first_name|capfirst }} {{ request.user.last_name|capfirst }}</b>
                {% if UserProfileInfo.profile_image %}
                  <img src="{{ UserProfileInfo.profile_image.url }}" class="img-fluid w-100" style="height:65px !important" alt="" >
                {% else %}
                    <img src="{% static 'default_testimonial.jpg' %}" class="img-fluid w-100" style="height:65px !important" alt="">
                {% endif %}
                
            </a>
            <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action {% if request.path == '/dashboard/' %} active {% endif %}" aria-current="true"> Dashboard </a>
            <a href="{% url 'bookingList' %}" class="list-group-item list-group-item-action {% if request.path == '/booking-list/' %} active {% endif %}">Booking List</a>
            <a href="{% url 'travelEnquiry' %}" class="list-group-item list-group-item-action {% if request.path == '/travel-enquiry/' %} active {% endif %}"> Travel Enquiry </a>
            <a href="{% url 'userGallery' %}" class="list-group-item list-group-item-action {% if request.path == '/user-gallery/' %} active {% endif %}">My Gallery</a>
            <a href="{% url 'userProfile' %}" class="list-group-item list-group-item-action {% if request.path == '/user-profile/' %} active {% endif %}"> Update Profile</a>
            <a href="{% url 'changePassword' %}" class="list-group-item list-group-item-action {% if request.path == '/change-password/' %} active {% endif %}"> Account Settings</a>
            <a href="{% url 'logout' %}" class="list-group-item list-group-item-action"><i class="fas fa-power-off me-2"></i>  Log Out</a>
        </div>
    </div>
</div>

Travel inquiry and package booking system/dj_19/templates/pages/userInfo/travel_enquiry.html
{% extends 'main_templates.html' %}
{% block content %}
{% load static %}
<!-- Header Start -->
{% include 'include/breadcrumb.html' %}
<!-- Header End -->
<!-- 404 Start -->
<div class="container-fluid py-5">
   <div class="container py-0 text-center">
      <div class="row msg">
         <div class="col-lg-12 col-md-12 mx-auto">
            {% if messages %}
               {% for message in messages %}
                  <div class="alert {% if message.tags == 'error' %} alert-danger {% else  %}  alert-success {% endif %} alert-dismissible">
                        {{ message }} 
                  </div>
               {% endfor %}
            {% endif %}
         </div>
      </div>
      <div class="row">
         {% include 'pages/userInfo/side_bar.html' %}
         <div class="col-lg-10 col-md-12">
            <div class="row">
               <div class="col-lg-12 col-md-12">
                  <div class="card text-start">
                     <div class="card-header">
                        Travel Enquiry
                        <div class="float-right"><a href="{% url 'booking' %}" class="btn btn-primary rounded-pill py-0 px-4 ms-lg-4">Book Now</a></div>
                     </div>
                     <div class="card-body">
                        <table id="example" class="example table table-striped table-bordered">
                           <thead>
                              <tr>
                                 <th>#</th>
                                 <th>Name</th>
                                 <th>Departure date</th>
                                 <th>No Days</th>
                                 <th>No Person</th>
                                 <th>Hotel type</th>
                                 <th>Destination</th>
                                 <th>Country</th>
                                 <th>Quotation</th>
                                 <th>Action</th>
                              </tr>
                           </thead>
                           <tbody>
                              {% for enquery in travel_enquiry_list %}
                              <tr>
                                 <td>{{forloop.counter}}</td>
                                 <td>{{enquery.name}}</td>
                                 <td>{{enquery.departure_date}}</td>
                                 <td>{{ enquery.duration }} Day{{ enquery.duration|pluralize }}</td>
                                 <td>{{enquery.no_person}}</td>
                                 <td>{{enquery.get_hotel_type_display}}</td>
                                 <td>{{enquery.destination}}</td>
                                 <td>{{enquery.country}}</td>
                                 <td class="text-center"> 
                                    {% if enquery.travelEnquiry_quotationInfo.exists %}

                                        <button type="button" class="btn btn-info btn-sm text-white rounded-0" onclick="displayQuotation('{{ enquery.id }}')">Received</button> 
                                    {% else %}
                                       <span class="text-danger">No Quotation</span>
                                    {% endif %}
                                 </td>
                                 <td>
                                    <button type="button" class="btn btn-primary btn-sm" onclick="displayTravelEnquiry('{{ enquery.id }}')"><i class="fa fa-eye" aria-hidden="true"></i></button>
                                    <button type="button" class="btn btn-danger btn-sm" onclick="confirmDeleteItem('{{ enquery.id }}','Enquiry')"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                 </td>
                              </tr>
                              {% endfor %}
                               
                           </tbody> 
                        </table>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>


<!-- The Display Travel Enquiry On  Modal -->
<div class="modal fade" id="myDisplayTravelEnquiryModal">
   <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
         <!-- Modal Header -->
         <div class="modal-header">
            <h4 class="modal-title">Travel Enquiry</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
         </div>
         <!-- Modal body -->
         <div class="modal-body">   
               <div class="row">
                  <div class="col-md-6">
                     <table class="table table-bordered">
                           
                           <tbody>
                              <tr>
                                 <th colspan="2" class="bg-primary text-white">Basic Info</th> 
                              </tr>
                              <tr>
                                 <th>Name</th>
                                 <td id="dte_name"></td> 
                              </tr>
                              <tr>
                                 <th>Email</th>
                                 <td id="dte_email"></td> 
                              </tr>
                              <tr>
                                 <th>Phone</th>
                                 <td id="dte_phone"></td> 
                              </tr>
                              <tr>
                                 <th>Created Date</th>
                                 <td id="dte_created_date"></td> 
                              </tr>
                              <tr>
                                 <th colspan="2" class="bg-primary text-white">Travel Details </th> 
                              </tr>
                              <tr>
                                 <th>Departure date</th>
                                 <td id="dte_departure_date"></td> 
                              </tr>
                              <tr>
                                 <th>Destination</th>
                                 <td id="dte_destination"></td> 
                              </tr>
                              <tr>
                                 <th>Country</th>
                                 <td id="dte_country"></td> 
                              </tr>
                              
                           </tbody>
                        </table> 
                  </div>
                  <div class="col-md-6">
                     <table class="table table-bordered">
                           
                           <tbody>
                               
                              <tr>
                                 <th colspan="2" class="bg-primary text-white">Hotel Details</th> 
                              </tr>
                              <tr>
                                 <th>Hotel type</th>
                                 <td id="dte_hotel_type"></td> 
                              </tr>
                              <tr>
                                 <th>No Days</th>
                                 <td id="dte_no_days"></td> 
                              </tr>
                              <tr>
                                 <th>No Person</th>
                                 <td id="dte_no_person"></td> 
                              </tr>
                              <tr>
                                 <th>Category</th>
                                 <td id="dte_category"></td> 
                              </tr>
                              <tr>
                                 <th colspan="2" class="bg-primary text-white">Additional info</th> 
                              </tr>
                              <tr>
                                 <td colspan="2">
                                    <div class="" id="dte_additional_info" style="height: 105px;overflow-y: scroll;"></div> 
                                 </td> 
                              </tr>
                               
                              
                           </tbody>
                        </table> 
                  </div>
               </div> 
         </div>
         <!-- Modal footer -->
         <div class="modal-footer"> 
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>  



<!-- The Display Quotation On  Modal -->
<div class="modal fade" id="myDisplayQuotationModal">
   <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
         <!-- Modal Header -->
         <div class="modal-header">
            <h4 class="modal-title">Quotation Info</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
         </div>
         <!-- Modal body -->
         <div class="modal-body">   
               <div class="row">
                  <div class="col-md-12">
                     <table class="table table-bordered">
                           <tbody>
                              <tr>
                                 <th>Price</th>
                                 <td id="dq_price"></td> 
                              </tr>
                              <tr>
                                 <th>Quotation Deacription</th>
                                 <td id="dq_quotation_deacription"></td> 
                              </tr>
                              <tr>
                                 <td colspan="2" class="text-center">
                                    <a href="#" id="dq_btn_booked" class="btn btn-primary">Booked</a>
                                 </td> 
                              </tr>
                           </tbody>
                        </table> 
                  </div>
                   
               </div> 
         </div> 
      </div>
   </div>
</div> 
{% endblock %}